### ISSUE TITLE
Not compatible with latest versions of Angular (12)

### ISSUE THREAD

**Issue by MoAsmar** [luly-8k/ngx-skeleton-smart-repo#1]
Please update peerDependencies to the latest version of angular (12) !

**Comment by jhimelymendoza** [comment]
Hello, To upload the version of angular we have to check the compatibility with the graphics libraries, but currently we have tested it with angular 10 and it works, you can tell us specifically what error you get when you use it in angular 12

**Comment by MoAsmar** [comment]
> Hello, To upload the version of angular we have to check the compatibility with the graphics libraries, but currently we have tested it with angular 10 and it works, you can tell us specifically what error you get when you use it in angular 12

![image](https://user-images.githubusercontent.com/8542126/137266965-c6d15ef2-fdc8-41d8-a404-07a19b4d8548.png)

**Comment by jhimelymendoza** [comment]
Hi, well we will be working on an update to the latest versions of angular

**Comment by MoAsmar** [comment]
Hello @jhimelymendoza, any updates? I am using this component but I had to update to the latest angular so please if you can fix this soon.

**Comment by jhimelymendoza** [comment]
We are working on the migration, it is something complex because to migrate to version 12 of angular you have to go through the previous versions 9, 10, 11 and 12. We are currently on the 10th and doing third party library updates that also need to be updated

**Comment by jhimelymendoza** [comment]
> Hello @jhimelymendoza, any updates? I am using this component but I had to update to the latest angular so please if you can fix this soon.

Hello, you can try this version of the library that are already in version 10 of angular and I tried with version 12 of angular and it works
https://www.npmjs.com/package/ngx-smart-skeleton/v/2.0.0-beta

**Comment by MoAsmar** [comment]
> We are working on the migration, it is something complex because to migrate to version 12 of angular you have to go through the previous versions 9, 10, 11 and 12. We are currently on the 10th and doing third party library updates that also need to be updated

I am doing the same but for a large-scale app, I can imagine the pain of doing this, I am at the same stage currently stopped at 10!

**Comment by jhimelymendoza** [comment]
> > We are working on the migration, it is something complex because to migrate to version 12 of angular you have to go through the previous versions 9, 10, 11 and 12. We are currently on the 10th and doing third party library updates that also need to be updated
> 
> I am doing the same but for a large-scale app, I can imagine the pain of doing this, I am at the same stage currently stopped at 10!

Hi  we finished the migration to angular 12, I leave you the npm link with the update
Angular 8 => https://www.npmjs.com/package/ngx-smart-skeleton/v/1.0.6
Angular 10 => https://www.npmjs.com/package/ngx-smart-skeleton/v/2.0.0
Angular 11 => https://www.npmjs.com/package/ngx-smart-skeleton/v/3.0.0
Angular 12 => https://www.npmjs.com/package/ngx-smart-skeleton/v/4.0.0
